# Generated by Django 3.1.4 on 2020-12-26 12:37

import apps.blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20201226_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Title')),
                ('title_fa', models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Title')),
                ('title_en', models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Title')),
                ('total_documents', models.PositiveSmallIntegerField(verbose_name='Total Documents')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Name')),
                ('total_documents', models.PositiveSmallIntegerField(verbose_name='Total Documents')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Title')),
                ('title_fa', models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Title')),
                ('title_en', models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle')),
                ('subtitle_fa', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle')),
                ('subtitle_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtitle')),
                ('document_file', models.URLField(verbose_name='URL')),
                ('cover', sorl.thumbnail.fields.ImageField(upload_to='', validators=[apps.blog.models.validate_image], verbose_name='Cover')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_fa', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_fa', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
                ('categories', models.ManyToManyField(related_name='categorized_documents', to='documents.DocumentCategory', verbose_name='Categories')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_documents', to='documents.documenttype', verbose_name='Type')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.airtrafficcontroller', verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('-created',),
            },
        ),
    ]
