# Generated by Django 3.1.4 on 2020-12-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_fa',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='total_documents',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total Documents'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='total_documents',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total Documents'),
        ),
    ]
