# Generated by Django 3.1.4 on 2020-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201226_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique_for_date='created', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
