# Generated by Django 3.1.4 on 2020-12-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20201226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='total_documents',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Total Documents'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='total_documents',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Total Documents'),
        ),
    ]
