# Generated by Django 3.1.4 on 2020-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20201227_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('pdfs', 'PDFs'), ('videos', 'Videos'), ('voices', 'Voices'), ('others', 'Other formats')], default='no_file', max_length=50, verbose_name='Type'),
        ),
    ]
