# Generated by Django 3.1.4 on 2020-12-23 11:01

import apps.blog.models
import ckeditor.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('active', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Active')),
                ('public', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='public')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='Publish')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hit Count',
                'verbose_name_plural': 'Hit Count',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, unique_for_date='publish', verbose_name='Slug')),
                ('descrip', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('descrip_fa', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('descrip_en', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Body')),
                ('body_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Body')),
                ('body_en', ckeditor.fields.RichTextField(null=True, verbose_name='Body')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Status')),
                ('public', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Public')),
                ('international', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='International')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='An icon-tag from fontawesome.com', max_length=250, null=True, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=apps.blog.models.get_upload_to, validators=[apps.blog.models.validate_image], verbose_name='Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
            },
        ),
    ]
