# Generated by Django 3.1.4 on 2021-01-01 17:14

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201226_1416'),
    ]

    operations = [
        TrigramExtension(),
    ]
