# Generated by Django 3.1.4 on 2020-12-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Medias'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.SlugField(default='', verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='media',
            field=models.CharField(choices=[('<!--Facebook--><a hrf="%(link)s" type="button" title="Facebook" class="btn-floating btn-large btn-fb"><i class="fab fa-facebook-f"></i></a>', 'Facebook'), ('<!--Twitter--><a hrf="%(link)s" type="button" title="Twitter" class="btn-floating btn-large btn-tw"><i class="fab fa-twitter"></i></a>', 'Twitter'), ('<!--Instagram--><a hrf="%(link)s" type="button" title="Instagram" class="btn-floating btn-large btn-ins"><i class="fab fa-instagram"></i></a>', 'Instagram'), ('<!--Telegram--><a hrf="%(link)s" type="button" title="Telegram" class="btn-floating btn-large btn-blue"><i class="fab fa-telegram-plane"></i></a>', 'Telegram'), ('<!--Email--><a hrf="%(link)s" type="button" title="Email" class="btn-floating btn-large btn-email"><i class="fas fa-envelope"></i></a>', 'Email')], default='', max_length=250, verbose_name='Media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airtrafficcontroller',
            name='social_links',
            field=models.ManyToManyField(blank=True, null=True, related_name='linked_user', to='users.SocialMedia', verbose_name='Social links'),
        ),
    ]
