# Generated by Django 3.1.4 on 2020-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201223_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='media',
            field=models.CharField(choices=[('<!--Facebook--><a href="%(link)s" type="button" title="Facebook" class="btn-floating btn-large btn-fb"><i class="fab fa-facebook-f"></i></a>', 'Facebook'), ('<!--Twitter--><a href="%(link)s" type="button" title="Twitter" class="btn-floating btn-large btn-tw"><i class="fab fa-twitter"></i></a>', 'Twitter'), ('<!--Instagram--><a href="%(link)s" type="button" title="Instagram" class="btn-floating btn-large btn-ins"><i class="fab fa-instagram"></i></a>', 'Instagram'), ('<!--Telegram--><a href="%(link)s" type="button" title="Telegram" class="btn-floating btn-large btn-blue"><i class="fab fa-telegram-plane"></i></a>', 'Telegram'), ('<!--Email--><a href="%(link)s" type="button" title="Email" class="btn-floating btn-large btn-email"><i class="fas fa-envelope"></i></a>', 'Email')], max_length=250, verbose_name='Media'),
        ),
    ]
