# Generated by Django 3.1.4 on 2020-12-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201223_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='media',
            new_name='_media',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='link',
            new_name='user_link',
        ),
    ]
