# Generated by Django 3.1.4 on 2020-12-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201223_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtrafficcontroller',
            name='maried',
            field=models.BooleanField(choices=[(False, 'Single'), (True, 'Maried')], default=True, verbose_name='Maried'),
        ),
    ]
