# Generated by Django 3.1.4 on 2020-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201225_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='user_link',
            field=models.URLField(unique=True, verbose_name='Link'),
        ),
    ]
