# Generated by Django 3.1.4 on 2021-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='acknowledged',
            field=models.BooleanField(default=False, verbose_name='Acknowledged'),
        ),
    ]
