# Generated by Django 3.1.4 on 2021-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_fa',
            field=models.CharField(max_length=250, null=True, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
