# Generated by Django 3.1.4 on 2021-01-11 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210106_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_fa',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
