# Generated by Django 3.1.4 on 2021-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210111_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtrafficcontroller',
            name='template',
            field=models.CharField(default='', max_length=50, verbose_name='tempalte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
