# Generated by Django 3.1.4 on 2021-01-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210119_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtrafficcontroller',
            name='template',
        ),
    ]
