# Generated by Django 3.1.4 on 2020-12-23 11:01

import apps.blog.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=254, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=254, null=True, verbose_name='Name')),
                ('logo', sorl.thumbnail.fields.ImageField(upload_to='logo/', validators=[apps.blog.models.validate_image], verbose_name='Logo')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('short_description_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('short_description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Short Description')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('long_description_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Long Description')),
                ('long_description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Long Description')),
                ('footer_description', ckeditor.fields.RichTextField(verbose_name='Footer Description')),
                ('footer_description_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Footer Description')),
                ('footer_description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Footer Description')),
                ('timetable_intro', ckeditor.fields.RichTextField(verbose_name='Timetable intro')),
                ('contact_intro', ckeditor.fields.RichTextField(verbose_name='Contact us intro')),
                ('phone1', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Please enter numbers, or switch your keyboard to `en`.')], verbose_name='Phone (main)')),
                ('phone2', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Please enter numbers, or switch your keyboard to `en`.')], verbose_name='Phone')),
                ('fax', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Please enter numbers, or switch your keyboard to `en`.')], verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=254, verbose_name='Address')),
                ('address_fa', models.CharField(max_length=254, null=True, verbose_name='Address')),
                ('address_en', models.CharField(max_length=254, null=True, verbose_name='Address')),
                ('darken_logo', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Darken Logo')),
            ],
            options={
                'verbose_name': 'Iran-ATCA',
                'verbose_name_plural': 'Iran-ATCA',
            },
        ),
        migrations.CreateModel(
            name='CompanySocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.CharField(help_text='An icon-tag from fontawesome.com', max_length=250, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Company Social Link',
                'verbose_name_plural': 'Company Social Links',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('client_ip', models.GenericIPAddressField(verbose_name='ClientIP')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', ckeditor.fields.RichTextField(verbose_name='Introduction')),
            ],
            options={
                'verbose_name': 'Management Team',
                'verbose_name_plural': 'Management Teams',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('name_fa', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('public', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Public')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=254, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=254, null=True, verbose_name='Title')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Useful Link',
                'verbose_name_plural': 'Useful Links',
            },
        ),
    ]
