# Generated by Django 3.1.4 on 2020-12-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementteam',
            name='headFR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headFR_teams', to='users.airtrafficcontroller', verbose_name='Head of FR'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='headPR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headPR_teams', to='users.airtrafficcontroller', verbose_name='Head of PR'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_teams', to='users.airtrafficcontroller', verbose_name='Secretary'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='secretary_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to='users.airtrafficcontroller', verbose_name='Secretary-General'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='treasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasured_teams', to='users.airtrafficcontroller', verbose_name='Treasure'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='veep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veeped_teams', to='users.airtrafficcontroller', verbose_name='Veep'),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardend_teams', to='users.airtrafficcontroller', verbose_name='Warden'),
        ),
        migrations.AddField(
            model_name='company',
            name='social_links',
            field=models.ManyToManyField(to='company.CompanySocialLink', verbose_name='Social Links'),
        ),
    ]
