# Generated by Django 3.1.4 on 2020-12-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums_admin', to='users.airtrafficcontroller', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(related_name='forums_joined', to='users.AirTrafficController', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='chat',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='forum.forum', verbose_name='Forum'),
        ),
        migrations.AddField(
            model_name='chat',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.chat', verbose_name='Reply'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='users.airtrafficcontroller', verbose_name='User'),
        ),
    ]
