# Generated by Django 3.1.4 on 2020-12-26 10:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(db_index=True, verbose_name='Content'),
        ),
    ]
