# Generated by Django 3.1.4 on 2021-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210101_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='invite_link',
            field=models.CharField(default='some text', max_length=250, verbose_name='Invite link'),
            preserve_default=False,
        ),
    ]
