# Generated by Django 3.1.4 on 2021-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210119_1937'),
        ('forum', '0006_auto_20210106_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='forums_joined', to='users.AirTrafficController', verbose_name='Members'),
        ),
    ]
